version: '3'

services:
  neo4j:
    image: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - data:/data
    deploy:
      # TODO traefik with multiple ports
      placement:
        constraints:
          - "node.role==worker"

volumes:
  data:
    driver: local
